name: Build And Release
run-name: R#${{ github.run_number }} (${{ github.event.repository.updated_at }}) [${{ github.event.head_commit.message }}]

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
    inputs:
      createRelease:
        description: "Create a release"
        required: false
        default: false
        type: boolean
  push:
    branches:
    - main

  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    outputs:
      ReleaseVersion: ${{ steps.set_version.outputs.ReleaseVersion }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Initialize directories
      shell: pwsh
      run: |
        mkdir binlogs

    - id: set_version
      name: Set up versioning
      shell: pwsh
      run: |
        $timestamp = Get-Date -Format "0.yyyyMMdd.${{ github.run_number }}"

        $Year = Get-Date -Format "yyyy"
        $Month = Get-Date -Format "MM"
        $Day = Get-Date -Format "dd"
        $CommitHash = $Env:GITHUB_SHA
        $ShortCommitHash = $CommitHash.Substring(0, 8)
        $InformationalVersion = "$Year.$Month.$Day"
        $ReleaseVersion = "$timestamp"

        echo "InformationalVersion=$InformationalVersion" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "ReleaseVersion=$ReleaseVersion" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

    - name: Publish
      shell: pwsh
      run: |
        foreach ($runtimeId in @("win-x64", "linux-x64")) {
          dotnet publish src/FastDownload.csproj -o publish/$runtimeId "/bl:binlogs/${runtimeId}.binlog" `
            -r $runtimeId --self-contained /p:PublishSingleFile=true /p:EnableNugetPackagePublishing=false `
            /p:EnableBinaryCheck=false /p:Configuration=Release /p:PublishAot=false
        }

    - name: Upload Binaries
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: binaries
        path: publish

    - name: Upload Binlogs
      if: always()
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: ${{ github.job }}-binlogs
        path: binlogs

  test:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Run Tests
      shell: pwsh
      run: dotnet test tests/FastDownload.Tests.csproj

  release:
    runs-on: windows-latest
    needs: [build, test]
    if : github.event.inputs.createRelease == 'true'

    steps:
    - name: Download Index Artifact
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: binaries
        path: publish

    - name: Create GitHub Release
      uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
      with:
        name: ${{ needs.build.outputs.ReleaseVersion }}
        tag_name: ${{ needs.build.outputs.ReleaseVersion }}
        prerelease: true
        body: |
          Release version: ${{ needs.build.outputs.ReleaseVersion }}
        files: |
          publish/win-x64/fastdownload.exe
          publish/linux-x64/fastdownload